process.roles=broker
node.id=5

listeners=PLAINTEXT://192.0.2.22:9092
advertised.listeners=PLAINTEXT://192.0.2.22:9092
inter.broker.listener.name=PLAINTEXT

controller.listener.names=CONTROLLER
controller.quorum.voters=1@192.0.2.11:9093,2@192.0.2.12:9093,3@192.0.2.13:9093

log.dirs=/var/lib/kafka/data

num.partitions=3
default.replication.factor=2
min.insync.replicas=1
offsets.topic.replication.factor=2
transaction.state.log.replication.factor=2
transaction.state.log.min.isr=1

group.initial.rebalance.delay.ms=0
