# ============================================================
# Kafka Controller 02 — KRaft / SASL-PLAIN / ACL
# ============================================================
# Role: controller only | node.id: 2
# Documentation address: <CONTROLLER02_HOST>
# Replace all CHANGE_ME_* values before deployment.
# ============================================================

process.roles=controller
node.id=2

listeners=CONTROLLER://<CONTROLLER02_HOST>:9093
controller.listener.names=CONTROLLER
listener.security.protocol.map=CONTROLLER:SASL_PLAINTEXT
sasl.enabled.mechanisms=PLAIN
sasl.mechanism.controller.protocol=PLAIN
listener.name.controller.plain.sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required username="controller02" password="CHANGE_ME_CONTROLLER02_PASSWORD" user_broker01="CHANGE_ME_BROKER01_PASSWORD" user_broker02="CHANGE_ME_BROKER02_PASSWORD" user_broker03="CHANGE_ME_BROKER03_PASSWORD" user_controller01="CHANGE_ME_CONTROLLER01_PASSWORD" user_controller02="CHANGE_ME_CONTROLLER02_PASSWORD" user_controller03="CHANGE_ME_CONTROLLER03_PASSWORD" user_kafka-admin="CHANGE_ME_KAFKA_ADMIN_PASSWORD" user_filebeat="CHANGE_ME_FILEBEAT_PASSWORD" user_logstash="CHANGE_ME_LOGSTASH_PASSWORD" user_akhq="CHANGE_ME_AKHQ_PASSWORD" user_collector="CHANGE_ME_COLLECTOR_PASSWORD" user_app="CHANGE_ME_APP_PASSWORD";

controller.quorum.voters=1@<CONTROLLER01_HOST>:9093,2@<CONTROLLER02_HOST>:9093,3@<CONTROLLER03_HOST>:9093

authorizer.class.name=org.apache.kafka.metadata.authorizer.StandardAuthorizer
allow.everyone.if.no.acl.found=false
super.users=User:kafka-admin;User:broker01;User:broker02;User:broker03;User:controller01;User:controller02;User:controller03

auto.create.topics.enable=false
log.dirs=/var/lib/kafka/data
group.initial.rebalance.delay.ms=0
