filebeat.config.inputs:
  enabled: true
  path: /usr/share/filebeat/inputs/*.yml
  reload.enabled: false

output.kafka:
  hosts: ["${KAFKA_BOOTSTRAP_SERVERS}"]
  topic: '${KAFKA_TOPIC}'
  partition.round_robin:
    reachable_only: false
  required_acks: 1
  compression: gzip
  max_message_bytes: 1000000

  # Kafka authentication: SASL/PLAIN
  username: '${KAFKA_USERNAME}'
  password: '${KAFKA_PASSWORD}'
  sasl.mechanism: PLAIN
  security.protocol: SASL_PLAINTEXT

logging.level: info
logging.to_files: true
logging.files:
  path: /usr/share/filebeat/logs
  name: filebeat
  keepfiles: 7
  permissions: 0644
